[rospy.client][INFO] 2020-04-10 21:05:11,757: init_node, name[/gps_heading], pid[5767]
[xmlrpc][INFO] 2020-04-10 21:05:11,758: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 21:05:11,758: Started XML-RPC server [http://juan:34975/]
[rospy.init][INFO] 2020-04-10 21:05:11,759: ROS Slave URI: [http://juan:34975/]
[rospy.impl.masterslave][INFO] 2020-04-10 21:05:11,759: _ready: http://juan:34975/
[rospy.registration][INFO] 2020-04-10 21:05:11,760: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 21:05:11,761: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 21:05:11,859: registered with master
[rospy.rosout][INFO] 2020-04-10 21:05:11,860: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 21:05:11,873: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 21:05:11,891: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 21:05:11,978: topic[/tcpvel] adding connection to [http://juan:35325/], count 0
[rospy.internal][INFO] 2020-04-10 21:05:12,035: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 21:05:12,061: topic[/heading] adding connection to [/rostopic_5735_1586552658538], count 0
[rospy.internal][INFO] 2020-04-10 21:05:12,242: topic[/heading] adding connection to [/gps_to_pose_conversion_node], count 1
[rospy.internal][INFO] 2020-04-10 21:35:34,587: topic[/heading] removing connection to /rostopic_5735_1586552658538
[rospy.internal][WARNING] 2020-04-10 21:36:21,462: Unknown error initiating TCP/IP socket to juan:38175 (http://juan:35325/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-04-10 21:36:21,462: topic[/tcpvel] removing connection to http://juan:35325/
[rospy.core][INFO] 2020-04-10 21:36:27,596: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2020-04-10 21:36:27,607: unclean shutdown
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/registration.py", line 372, in cleanup
    multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1006, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1069, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 907, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 869, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 846, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 113] No route to host

[rospy.internal][INFO] 2020-04-10 21:36:27,607: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-04-10 21:36:27,607: topic[/heading] removing connection to /gps_to_pose_conversion_node
[rospy.impl.masterslave][INFO] 2020-04-10 21:36:27,608: signal-2
[rospy.core][INFO] 2020-04-10 21:36:27,724: signal_shutdown [atexit]
