[rospy.client][INFO] 2020-04-10 15:27:52,844: init_node, name[/rostopic_2852_1586532472795], pid[2852]
[xmlrpc][INFO] 2020-04-10 15:27:52,844: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-04-10 15:27:52,845: Started XML-RPC server [http://juan:41253/]
[rospy.init][INFO] 2020-04-10 15:27:52,845: ROS Slave URI: [http://juan:41253/]
[rospy.impl.masterslave][INFO] 2020-04-10 15:27:52,845: _ready: http://juan:41253/
[rospy.registration][INFO] 2020-04-10 15:27:52,845: Registering with master node http://tractor:11311/
[xmlrpc][INFO] 2020-04-10 15:27:52,846: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-04-10 15:27:52,945: registered with master
[rospy.rosout][INFO] 2020-04-10 15:27:52,946: initializing /rosout core topic
[rospy.rosout][INFO] 2020-04-10 15:27:52,965: connected to core topic /rosout
[rospy.simtime][INFO] 2020-04-10 15:27:53,077: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-04-10 15:27:53,321: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-04-10 15:27:53,349: topic[/heading] adding connection to [http://juan:37329/], count 0
[rospy.core][INFO] 2020-04-10 15:28:57,541: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-04-10 15:28:57,563: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-04-10 15:28:57,563: topic[/heading] removing connection to http://juan:37329/
[rospy.topics][ERROR] 2020-04-10 15:28:57,564: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2020-04-10 15:28:57,565: signal-2
[rospy.internal][WARNING] 2020-04-10 15:28:57,565: Unknown error initiating TCP/IP socket to juan:38815 (http://juan:37329/): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/usr/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2020-04-10 15:28:57,697: signal_shutdown [atexit]
